# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/models.tcn.ipynb.

# %% auto 0
__all__ = ['TCN']

# %% ../../nbs/models.tcn.ipynb 5
from typing import List, Optional

import torch
import torch.nn as nn

from ..losses.pytorch import MAE
from ..common._base_recurrent import BaseRecurrent
from ..common._modules import MLP, TemporalConvolutionEncoder
from torch.nn import TransformerEncoder, TransformerEncoderLayer

# %% ../../nbs/models.tcn.ipynb 7
class TCN(BaseRecurrent):
    """TCN

    Temporal Convolution Network (TCN), with MLP decoder.
    The historical encoder uses dilated skip connections to obtain efficient long memory,
    while the rest of the architecture allows for future exogenous alignment.

    **Parameters:**<br>
    `h`: int, forecast horizon.<br>
    `input_size`: int, maximum sequence length for truncated train backpropagation. Default -1 uses all history.<br>
    `inference_input_size`: int, maximum sequence length for truncated inference. Default -1 uses all history.<br>
    `kernel_size`: int, size of the convolving kernel.<br>
    `dilations`: int list, ontrols the temporal spacing between the kernel points; also known as the à trous algorithm.<br>
    `encoder_hidden_size`: int=200, units for the TCN's hidden state size.<br>
    `encoder_activation`: str=`tanh`, type of TCN activation from `tanh` or `relu`.<br>
    `context_size`: int=10, size of context vector for each timestamp on the forecasting window.<br>
    `decoder_hidden_size`: int=200, size of hidden layer for the MLP decoder.<br>
    `decoder_layers`: int=2, number of layers for the MLP decoder.<br>
    `futr_exog_list`: str list, future exogenous columns.<br>
    `hist_exog_list`: str list, historic exogenous columns.<br>
    `stat_exog_list`: str list, static exogenous columns.<br>
    `loss`: PyTorch module, instantiated train loss class from [losses collection](https://nixtla.github.io/neuralforecast/losses.pytorch.html).<br>
    `max_steps`: int=1000, maximum number of training steps.<br>
    `learning_rate`: float=1e-3, Learning rate between (0, 1).<br>
    `valid_batch_size`: int=None, number of different series in each validation and test batch.<br>
    `num_lr_decays`: int=-1, Number of learning rate decays, evenly distributed across max_steps.<br>
    `early_stop_patience_steps`: int=-1, Number of validation iterations before early stopping.<br>
    `val_check_steps`: int=100, Number of training steps between every validation loss check.<br>    `batch_size`: int=32, number of differentseries in each batch.<br>
    `scaler_type`: str='robust', type of scaler for temporal inputs normalization see [temporal scalers](https://nixtla.github.io/neuralforecast/common.scalers.html).<br>
    `random_seed`: int=1, random_seed for pytorch initializer and numpy generators.<br>
    `num_workers_loader`: int=os.cpu_count(), workers to be used by `TimeSeriesDataLoader`.<br>
    `drop_last_loader`: bool=False, if True `TimeSeriesDataLoader` drops last non-full batch.<br>
    `alias`: str, optional,  Custom name of the model.<br>
    `optimizer`: Subclass of 'torch.optim.Optimizer', optional, user specified optimizer instead of the default choice (Adam).<br>
    `optimizer_kwargs`: dict, optional, list of parameters used by the user specified `optimizer`.<br>
    `lr_scheduler`: Subclass of 'torch.optim.lr_scheduler.LRScheduler', optional, user specified lr_scheduler instead of the default choice (StepLR).<br>
    `lr_scheduler_kwargs`: dict, optional, list of parameters used by the user specified `lr_scheduler`.<br>
    `dataloader_kwargs`: dict, optional, list of parameters passed into the PyTorch Lightning dataloader by the `TimeSeriesDataLoader`. <br>
    `**trainer_kwargs`: int,  keyword trainer arguments inherited from [PyTorch Lighning's trainer](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.trainer.trainer.Trainer.html?highlight=trainer).<br>
    """

    # Class attributes
    SAMPLING_TYPE = "recurrent"
    EXOGENOUS_FUTR = True
    EXOGENOUS_HIST = True
    EXOGENOUS_STAT = True

    # constructor 
    def __init__(
        self,
        h: int,
        input_size: int = -1,
        inference_input_size: int = -1,
        kernel_size: int = 2,
        dilations: List[int] = [1, 2, 4, 8],
        encoder_hidden_size: int = 200,
        # menggunakan PReLU untuk menghindari data yang setelah masuk ke TCN hilang ketika datanya minus
        # karena kalau di ReLU jadi 0
        encoder_activation: str = "PReLU",
        context_size: int = 10,
        decoder_hidden_size: int = 200,
        decoder_layers: int = 2,
        futr_exog_list=None,
        hist_exog_list=None,
        stat_exog_list=None,
        loss=MAE(),
        valid_loss=None,
        max_steps: int = 1000,
        learning_rate: float = 1e-3,
        num_lr_decays: int = -1,
        early_stop_patience_steps: int = -1,
        val_check_steps: int = 100,
        batch_size: int = 32,
        valid_batch_size: Optional[int] = None,
        scaler_type: str = "robust",
        random_seed: int = 1,
        num_workers_loader=0,
        drop_last_loader=False,
        optimizer=None,
        optimizer_kwargs=None,
        lr_scheduler=None,
        lr_scheduler_kwargs=None,
        dataloader_kwargs=None,
        debug_print=False,
        **trainer_kwargs
    ):
        if debug_print:
            self.forward = self.forward_with_print
            
        super(TCN, self).__init__(
            h=h,
            input_size=input_size,
            inference_input_size=inference_input_size,
            loss=loss,
            valid_loss=valid_loss,
            max_steps=max_steps,
            learning_rate=learning_rate,
            num_lr_decays=num_lr_decays,
            early_stop_patience_steps=early_stop_patience_steps,
            val_check_steps=val_check_steps,
            batch_size=batch_size,
            valid_batch_size=valid_batch_size,
            scaler_type=scaler_type,
            futr_exog_list=futr_exog_list,
            hist_exog_list=hist_exog_list,
            stat_exog_list=stat_exog_list,
            num_workers_loader=num_workers_loader,
            drop_last_loader=drop_last_loader,
            random_seed=random_seed,
            optimizer=optimizer,
            optimizer_kwargs=optimizer_kwargs,
            lr_scheduler=lr_scheduler,
            lr_scheduler_kwargs=lr_scheduler_kwargs,
            dataloader_kwargs=dataloader_kwargs,
            **trainer_kwargs
        )

        # ----------------------------------- Parse dimensions -----------------------------------#
        # TCN
        self.kernel_size = kernel_size
        self.dilations = dilations
        self.encoder_hidden_size = encoder_hidden_size
        self.encoder_activation = encoder_activation

        # Context adapter
        self.context_size = context_size

        # MLP decoder
        self.decoder_hidden_size = decoder_hidden_size
        self.decoder_layers = decoder_layers

        # TCN input size (1 for target variable y)
        input_encoder = 1 + self.hist_exog_size + self.stat_exog_size

        # ---------------------------------- Instantiate Model -----------------------------------#
        # Instantiate historic encoder
        self.hist_encoder = TemporalConvolutionEncoder(
            in_channels=input_encoder,
            out_channels=self.encoder_hidden_size,
            kernel_size=self.kernel_size,  # Almost like lags
            dilations=self.dilations,
            activation=self.encoder_activation,
        )
        
        # Transformer Encoder Layer
        transformer_layer = TransformerEncoderLayer(
            d_model=self.encoder_hidden_size,
            nhead=8,
            dim_feedforward=self.encoder_hidden_size,
            dropout=0.2,
            batch_first=False
        )
        self.transformer = TransformerEncoder(transformer_layer, num_layers=1)

        # Context adapter
        self.context_adapter = nn.Linear(
            in_features=self.encoder_hidden_size + self.futr_exog_size * h,
            out_features=self.context_size * h,
        )

        # Decoder MLP
        self.mlp_decoder = MLP(
            in_features=self.context_size + self.futr_exog_size,
            out_features=self.loss.outputsize_multiplier,
            hidden_size=self.decoder_hidden_size,
            num_layers=self.decoder_layers,
            activation="ReLU",
            dropout=0.0,
        )

        # parameter yang diperbaiki setiap iterasi
        # ada di fungsi weightening
        self.alpha_scale = nn.Parameter(torch.tensor(0.005))
        self.alpha_correction = nn.Parameter(torch.tensor(0.0))
        self.debug_print = debug_print

    # fungsinya untuk melakukan penyetaraan saat skip connection,
    # agar hasil fitur dari transformer tidak terlalu berubah jauh dari hasil tcn
    # untuk ditambahkan nantinya sebelum MLP
    # agar tidak menghilangkan data dari TCN
    # range nilai TCN -0.01 sampai 0.01 dan transformer tanpa weightening -1 sampai 1  
    def weightening(self):
        # hyper tanh merupakan fungsi aktivasi dikalikan dengan alpha_scale 
        # nilainya alpha_correction dan alpha_scale diperbaiki terus setiap iterasi
        return torch.tanh(self.alpha_correction) * self.alpha_scale

    # fungsi yang bertugas untuk memproses setiap input yang masuk di NAD-Tran
    def forward(self, windows_batch):
        # Mengambil data sample dan historic exogen
        # insample_y -> key dari hashmap input data 21 hari
        # encoder_input -> data input (21 hari)
        encoder_input = windows_batch["insample_y"]  # format: [batch_size, input_data (21 hari)]
        futr_exog = windows_batch["futr_exog"] # ga di panggil
        hist_exog = windows_batch["hist_exog"] # data historis (19 fitur dengan 21 hari)
        stat_exog = windows_batch["stat_exog"] # ga dipanggil

        # Concatenate y, historic and static inputs
        # [B, C, seq_len, 1] -> [B, seq_len, C]
        # Contatenate [ Y_t, | X_{t-L},..., X_{t} | S ]
        batch_size, seq_len = encoder_input.shape[:2] # mengambil batch_size dan data 21 hari sebelumnya 
        if self.hist_exog_size > 0:
            hist_exog = hist_exog.permute(0, 2, 1, 3).squeeze(
                -1
            )  # [B, X, seq_len, 1] -> [B, seq_len, X]
            encoder_input = torch.cat((encoder_input, hist_exog), dim=2) # digabungkan antara data input dan data feature historis lainnya

        # tidak dipanggil (template neuralforecast) ======
        if self.stat_exog_size > 0:
            stat_exog = stat_exog.unsqueeze(1).repeat(
                1, seq_len, 1
            )  # [B, S] -> [B, seq_len, S]
            encoder_input = torch.cat((encoder_input, stat_exog), dim=2)
        # ==============

        # Masuk ke proses TCN
        hasil_tcn = self.hist_encoder( # dilakukan proses ekstraksi dengan tcn
            encoder_input
        )  # format: [input_data_21, batch_size, ukuran_hasil_ekstraksi]
        

        # ini digunakan untuk skip connection nantinya
        # kegunaan skip connection fitur hasil TCN tidak hilang sepenuhnya melainkan tetap ada
        hasil_fitur_tcn_sementara = hasil_tcn
        
        # Masuk ke proses Transformer
        # Karena formatnya dari transformer itu [batch_size, input_data_21, ukuran_hasil_ekstraksi]
        # maka data sebelumnya diputar dari  [input_data_21, batch_size, ukuran_hasil_ekstraksi] 
        # menjadi [batch_size, input_data_21, ukuran_hasil_ekstraksi]

        # diputar (dengan fungsi permute)
        hasil_diputar = hasil_tcn.permute(1, 0, 2)  # hasilnya [batch_size, input_data_21, ukuran_hasil_ekstraksi]

        # masuk ke transformer
        # hasilnya [batch_size, input_data_21, hasil_ekstraksi_transformer]
        hasil_transformer = self.transformer(hasil_diputar)

        # setelah diputar dibalikkan lagi menjadi [input_data_21, batch_size, hasil_ekstraksi_transformer]
        hasil_transformer_yang_dikembalikan = hasil_transformer.permute(1, 0, 2)  # hasilnya [input_data_21, batch_size, hasil_ekstraksi_transformer]

        # dilakukan skip connection, lompatan dari hasil fitur tcn dengan hasil transforer yang telah diberikan scale   
        hasil_skip_connection = hasil_fitur_tcn_sementara + (hasil_transformer_yang_dikembalikan * self.weightening())

        # tidak dipanggil (template neuralforecast) ======
        if self.futr_exog_size > 0:
            futr_exog = futr_exog.permute(0, 2, 3, 1)[
                :, :, 1:, :
            ]  # [B, F, seq_len, 1+H] -> [B, seq_len, H, F]
            hidden_state = torch.cat(
                (hidden_state, futr_exog.reshape(batch_size, seq_len, -1)), dim=2
            )
        # ==============

        # Context adapter ===================
        # 1 hidden layer template neuralforecast
        context = self.context_adapter(hasil_skip_connection)
        context = context.reshape(batch_size, seq_len, self.h, self.context_size)
        # ================

        # tidak dipanggil (template neuralforecast) ======
        if self.futr_exog_size > 0:
            context = torch.cat((context, futr_exog), dim=-1)
        # ==============

        # Final forecast, untuk mendapatkan hasil prediksi
        output = self.mlp_decoder(context)

        # hasil prediksi termasuk nilai lossnya
        output = self.loss.domain_map(output)

        return output


    # Ini untuk debug yang diprint2
    def forward_with_print(self, windows_batch):

        # Parse windows_batch
        encoder_input = windows_batch["insample_y"]  # [B, seq_len, 1]
        futr_exog = windows_batch["futr_exog"]
        hist_exog = windows_batch["hist_exog"]
        stat_exog = windows_batch["stat_exog"]

        # Concatenate y, historic and static inputs
        # [B, C, seq_len, 1] -> [B, seq_len, C]
        # Contatenate [ Y_t, | X_{t-L},..., X_{t} | S ]
        batch_size, seq_len = encoder_input.shape[:2]
        if self.hist_exog_size > 0:
            hist_exog = hist_exog.permute(0, 2, 1, 3).squeeze(
                -1
            )  # [B, X, seq_len, 1] -> [B, seq_len, X]
            encoder_input = torch.cat((encoder_input, hist_exog), dim=2)
            if self.debug_print: print(f"Input Shape: {encoder_input.shape}")

        if self.stat_exog_size > 0:
            stat_exog = stat_exog.unsqueeze(1).repeat(
                1, seq_len, 1
            )  # [B, S] -> [B, seq_len, S]
            encoder_input = torch.cat((encoder_input, stat_exog), dim=2)

        # TCN forward
        hidden_state = self.hist_encoder(
            encoder_input
        )  # [B, seq_len, tcn_hidden_state]
        if self.debug_print: print(f"Output TCN Shape: {hidden_state.shape}")

        # Transformer with residual connection
        original_hidden = hidden_state
        if self.debug_print: print(f"Output After TCN: {hidden_state}")
        hidden_state = hidden_state.permute(1, 0, 2)  # [seq_len, B, D]
        hidden_state = self.transformer(hidden_state)
        hidden_state = hidden_state.permute(1, 0, 2)  # [B, seq_len, D]
        if self.debug_print: print(f"Output After Transformer: {hidden_state}")
        alpha = torch.tanh(self.alpha_correction) * self.alpha_scale
        if self.debug_print: print(f"Output Alpha: {alpha}")
        hidden_state = original_hidden + (hidden_state * alpha)
        if self.debug_print: print(f"Output Hidden State After Transformer: {hidden_state}")

        if self.futr_exog_size > 0:
            futr_exog = futr_exog.permute(0, 2, 3, 1)[
                :, :, 1:, :
            ]  # [B, F, seq_len, 1+H] -> [B, seq_len, H, F]
            hidden_state = torch.cat(
                (hidden_state, futr_exog.reshape(batch_size, seq_len, -1)), dim=2
            )

        # Context adapter
        if self.debug_print: print(f"Output Shape Before Context: {hidden_state.shape}")
        context = self.context_adapter(hidden_state)
        context = context.reshape(batch_size, seq_len, self.h, self.context_size)
        if self.debug_print: print(f"Output Shape After Context: {context.shape}")

        # Residual connection with futr_exog
        if self.futr_exog_size > 0:
            context = torch.cat((context, futr_exog), dim=-1)

        # Final forecast
        output = self.mlp_decoder(context)
        if self.debug_print: print(f"Output Shape After MLP: {output.shape}")
        output = self.loss.domain_map(output)

        return output
